- hosts: all
  vars_files:
    - vars/secrets.yml
  roles:
    - { role: geerlingguy.postfix }

  tasks:
    - name: Install mailutils
      apt:
        pkg:
          - mailutils
          - libsasl2-modules
    - name: Add relayhost
      lineinfile:
        path: /etc/postfix/main.cf
        regexp: ^relayhost
        line: relayhost = [{{ AWS_SES_SMTP_REGION }}]:587
    - name: Add postfix config
      blockinfile:
        path: /etc/postfix/main.cf
        block: |
          smtp_sasl_auth_enable = yes
          smtp_sasl_password_maps = hash:/etc/postfix/sasl_passwd
          smtp_sasl_security_options = noanonymous
          smtp_tls_security_level = encrypt
          header_size_limit = 4096000
          smtp_generic_maps = hash:/etc/postfix/generic
    - name: Add postfix map
      lineinfile:
        path: /etc/postfix/generic
        create: yes
        regexp: ^root noreply
        line: root noreply@e-o.no
      notify:
        - "do postmap mapping"
    - name: Add postfix map
      lineinfile:
        path: /etc/postfix/generic
        create: yes
        regexp: ^{{maint_user}} noreply
        line: "{{maint_user}} noreply@e-o.no"
      notify:
        - "do postmap mapping"
    - name: Add postfix map
      lineinfile:
        path: /etc/postfix/generic
        create: yes
        regexp: ^{{deploy_user}} noreply
        line: "{{deploy_user}} noreply@e-o.no"
      notify:
        - "do postmap mapping"
    - name: Create sasl for SES
      template:
        src: ./templates/sasl_passwd.j2
        dest: /etc/postfix/sasl_passwd
        owner: root
        group: root
        mode: 0600
      notify:
        - hash sasl
    - name: Change file ownership, group and permissions
      ansible.builtin.file:
        path: /etc/postfix/sasl_passwd.db
        owner: root
        group: root
        mode: '0600'

  handlers:
    - name: restart postfix
      service:
        name: postfix
        state: restarted
      listen: "do postmap mapping"
    - name: postmap mapping
      command: postmap /etc/postfix/generic
      listen: "do postmap mapping"
    - name: hash sasl
      command: postmap hash:/etc/postfix/sasl_passwd
      notify:
        - restart postfix
